function(steambridge_prepare_vcltl)
    set(version "5.3.1")
    set(hash "7a18799ed3aa84a225610a5447a56bc534c5c98ccb8dec05caba0e3f633431ad")
    set(cache "${PROJECT_SOURCE_DIR}/thirdparty/cache")
    file(MAKE_DIRECTORY "${cache}")
    file(LOCK "${cache}/VC-LTL.lock" GUARD FUNCTION TIMEOUT 300)
    if(EXISTS "${VC_LTL_Root}/.verified-sha256")
        file(READ "${VC_LTL_Root}/.verified-sha256" verified)
        string(STRIP "${verified}" verified)
        if(verified STREQUAL hash AND EXISTS "${VC_LTL_Root}/VC-LTL helper for cmake.cmake")
            return()
        endif()
    endif()
    set(archive "${cache}/VC-LTL-${version}.7z")
    if(NOT EXISTS "${archive}")
        file(DOWNLOAD "https://github.com/Chuyu-Team/VC-LTL5/releases/download/v${version}/VC-LTL-Binary.7z"
            "${archive}.download" EXPECTED_HASH "SHA256=${hash}" TLS_VERIFY ON STATUS status TIMEOUT 300)
        list(GET status 0 result)
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "VC-LTL download failed: ${status}")
        endif()
        file(RENAME "${archive}.download" "${archive}")
    endif()
    file(SHA256 "${archive}" actual)
    if(NOT actual STREQUAL hash)
        message(FATAL_ERROR "VC-LTL archive checksum mismatch: ${archive}")
    endif()
    file(MAKE_DIRECTORY "${VC_LTL_Root}")
    file(ARCHIVE_EXTRACT INPUT "${archive}" DESTINATION "${VC_LTL_Root}")
    file(WRITE "${VC_LTL_Root}/.verified-sha256" "${hash}\n")
endfunction()
